### ISSUE TITLE
dbmate dump doesn't work in official Docker image

### ISSUE THREAD

**Issue by ohueter** [amacneil/dbmate#114]
Running
```$ docker run --rm -it -v "$(pwd)"/db:/db amacneil/dbmate dump```
fails with
```Error: exec: "pg_dump": executable file not found in $PATH```
because pg_dump (and mysqldump) are not included in the `gcr.io/distroless/base` runtime image.

**Comment by amacneil** [comment]
This is working as intended for now (although I should document it).

Unfortunately, using a version of `pg_dump` or `mysqldump` which doesn't match your server version can lead to unexpected issues. There are obvious issues if you use an older client trying to connect to a newer server version, but I have also seen issues with a newer client trying to connect to an older client. I'm open to ideas for how to work around this, perhaps we could just bundle the binaries anyway and deal with potential errors, but for now if you want to use the schema dump features you need to use the single binary distribution rather than the docker container.

**Comment by ohueter** [comment]
Hi Adrian,

thank you for the clarification. I wasn't aware of that, but it makes sense. A small hint in the documentation would be very helpful and sufficient in my opinion. We'll set up our own Docker image, that's probably the best workaround.

Apart from that, I'd like to take this opportunity and thank you for your work on this great tool! It's a simple and straight-forward tool and I'm really pleased with it.

Cheers, Ole

**Comment by amacneil** [comment]
Fixed this in #157 - let me know how it goes!
