### ISSUE TITLE
Environment Variables within SQL Scripts

### ISSUE THREAD

**Issue by xemoka** [amacneil/dbmate#118]
Hello, 

I would like access to variables within the .env file from each .sql file; i.e.: if I have

```sh
# .env
ROLE="authentication"
ROLE_PASS="hunter2"
```

Then I could use a placeholder of 

```sql
-- 2020020319418_db_role.sql
create role :"ROLE" login password :'ROLE_PASS'
```

Is this of interest to folks or is this already possible and I just can't seem to see how? It doesn't seem like golang's _pq_ support's psql's `\set` type statements in scripts either. Maybe there's a way to do this through _pq_ I'm unaware of?

**Comment by amacneil** [comment]
Interesting idea. I don't think it's possible today.

I'm wondering if there are any clever ways to solve this. Doing basic string interpolation would be possible, but it could lead to some issues with improper escaping depending on whether you are using the variable as a literal string or as an identifier.

**Comment by xemoka** [comment]
In psql `\set variable value` results in `:variable` returning the value, if you need it quoted, you provide `:'variable'` or `:"variable"` and it outputs the quoted variable. 

Does go's _text/template_ provide a way to do this easily based on how .sql files are read into dbmate? I wish I was more versed in golang...

**Comment by amacneil** [comment]
I'm going to close this issue, since it doesn't seem like a critical feature for dbmate, and there doesn't seem to be any reasonable way to implement it.

Problems I can see:
* We don't do any sql parsing, so it's not safe to simply inject variables directly
* I don't think the golang `lib/pq` library we use allows you to set variables using the syntax you mentioned
* Anything we add should probably work cross-platform, and while `psql` appears to allow you to parameterize sql files, I don't think all databases do

Finally, I think you could fairly easily work around the lack of injected variables in dbmate by simply running a post-migration script or one-liner using `psql`.

I'm open to discussing further if someone can suggest an elegant way to do this while addressing the issues above.

**Comment by amacneil** [comment]
After thinking about this some more, I think the easiest way to add it would be to use the Go template library. So your migrations would end up something like this:

```
create role {{ .Role }} login password {{ .RolePass }}
```

and then maybe require that variables are explicitly specified when you invoke dbmate (so that we don't have to inherit/expose the entire environment):


```
$ dbmate up --parameter "Role=$ROLE"
```

We can escape the values as string literals by default, which should be safe for most uses.

That said, this feature would add complexity to dbmate, which goes against our general philosophy of keeping things simple, so for a simple one-liner like the above I think it would make more sense to just use psql. If someone has a more complex example where this feature would add a lot of value, please comment.

**Comment by wrbbz** [comment]
Hey, @amacneil, so what is the status of this feature request?

What is the solution?
The `--parameter` flag is abscent
The `\set` is `syntax error at or near "\"`

I'm trying to create var with value from env:
```
\set variable `echo "$SOME_VAR"`
```

According to [this one](https://stackoverflow.com/questions/18725880/using-an-environment-variable-in-a-psql-script) it should work.
As I understand, the second solution will not work due to the need of argument passing in `psql` script. 

P.S. both solutions (with `\set`) are not working due to:

> It doesn't seem like golang's pq support's psql's \set type statements in scripts either.

**Comment by amacneil** [comment]
Dbmate doesn't support this today. I'm on the fence as to whether we should support this feature - the whole philosophy of migrations is to provide a repeatable way of creating database state, and environment variables go against that.

I could possibly be convinced by a concrete example of where this is needed. So far the only suggestion above has been for setting a password, which is something that doesn't seem like it should belong in a migration anyway (as I suggested in another comment, could easily be solved by a `psql` one-liner).

If you feel it is necessary, can you explain more about your use case?

Also, even if we decide to add it, I don't have much time to devote to new feature development currently so this would need a PR contribution. But let's discuss whether it is a good idea first.

**Comment by marbemac** [comment]
In case it's helpful for anybody else, for the time being I just put together a little script to run before the `dbmate` migrate commands.

- It assumes migrations are kept in a `db/migrations-raw` folder rather than `db/migrations`.
- It copies all files from `db/migrations-raw` to `db/migrations`, replacing occurrences of `{{VAR_NAME}}` with environment values as it goes

For example, a migration file in `db/migrations-raw/123_init.sql` with contents `create role :{{ROLE}} login password :{{ROLE_PASS}}`, and environment variables `ROLE=user`, `ROLE_PASS=123`, will result in a `db/migrations/123_init.sql` file with contents `create role :user login password :123`.

The script is below. Run it along lines of `node process-raw.mjs`, or expose it as a cli, etc. It assumes it is run a folder that has `db/migrations-raw` inside of it (can configure w the vars below).

```mjs
import * as path from 'node:path';
import * as fs from 'node:fs/promises';

/** CONFIGURABLE */

const DEBUG = false; // Flip to true for some logging
const RAW_MIGRATIONS_DIR = path.join('db', 'migrations-raw');
const MIGRATIONS_DIR = path.join('db', 'migrations');

/** END CONFIGURABLE */

const log = (...args) => {
  if (DEBUG) {
    console.log(...args);
  }
};

const ENV_VAR_REGEX = /\{\{([\w|-]+)\}\}/g;

const processRawMigration = async migrationPath => {
  let fileContents = await fs.readFile(path.join(RAW_MIGRATIONS_DIR, migrationPath), 'utf8');
  log('Processing', migrationPath);

  const matches = [...new Set(Array.from(fileContents.matchAll(ENV_VAR_REGEX)).map(m => m[1]))];
  for (const match of matches) {
    const varValue = process.env[match];
    if (varValue === void 0) {
      log(`    [warn] no value found for env variable ${match}`);
      continue;
    }

    log(`    replacing ${match}`);
    fileContents = fileContents.replaceAll(`{{${match}}}`, varValue);
  }

  await fs.writeFile(path.join(MIGRATIONS_DIR, migrationPath), fileContents);
};

const prepMigrationsFolder = async () => {
  await fs.rm(MIGRATIONS_DIR, { recursive: true, force: true });
  await fs.mkdir(MIGRATIONS_DIR);
};

const processRawMigrations = async () => {
  const rawMigrationPaths = await fs.readdir(RAW_MIGRATIONS_DIR);
  if (!rawMigrationPaths || !rawMigrationPaths.length) {
    log(`No raw migrations found at "${path.resolve(RAW_MIGRATIONS_DIR)}", skipping raw migration processing`);
    return;
  }

  await prepMigrationsFolder();

  for (const rawMigrationPath of rawMigrationPaths) {
    await processRawMigration(rawMigrationPath);
  }
};

const run = async () => {
  await processRawMigrations();
};

void run();
```

**Comment by davidecavestro** [comment]
> After thinking about this some more, I think the easiest way to add it would be to use the Go template library. So your migrations would end up something like this:
> 
> ```
> create role {{ .Role }} login password {{ .RolePass }}
> ```
> 
> and then maybe require that variables are explicitly specified when you invoke dbmate (so that we don't have to inherit/expose the entire environment):
> 
> ```
> $ dbmate up --parameter "Role=$ROLE"
> ```
> 
> We can escape the values as string literals by default, which should be safe for most uses.
> 
> That said, this feature would add complexity to dbmate, which goes against our general philosophy of keeping things simple, so for a one-liner like the above I think it would make more sense to just use psql. If someone has a more complex example where this feature would add a lot of value, please comment.

I like the idea of exposing go template syntax as it generically stands out within SQL snippets.

I noticed dbmate migration parsing logic already has [support for optional arguments](https://github.com/amacneil/dbmate/blob/5d1b5214d1f613c7061f29d7f80219e8b59449ee/pkg/dbmate/migration.go#L137)
![image](https://user-images.githubusercontent.com/447917/235293665-c92c7b62-5091-4476-a828-91849905325b.png)
![image](https://user-images.githubusercontent.com/447917/235293738-f548782a-3235-46fa-9c24-6ca546158ccb.png)

So the parsing output mapping could be enhanced to support declaring **exposed env vars**, migration per migration.

i.e. a syntax like
`-- migrate:up env-var:ROLE env-var:ROLEPASS`
would limit both the set of exposed env vars (just explicitly declares ones) and the scope (just that particular up migration)

This  would somewhat mitigate the point
> We don't do any sql parsing, so it's not safe to simply inject variables directly

IMHO the complexity added this way would be negligible: add the option to existing _ParsedMigrationOptions_ and use its values to pass the raw sql through go templating (just if/when needed).

Side effects like templating syntax conflicts would be limited to migrations having that option enabled, of which migration author should be aware.

If it makes sense and need some help I could propose a PR.
