### ISSUE TITLE
postgres: migration and rollback at the schema level

### ISSUE THREAD

**Issue by jeff-cf** [amacneil/dbmate#132]
Hi Adrian,

This is more of a question/feature request than an issue.
We have multiple teams sharing the same schema in the same Postgres DB due to historical reasons, and now we would like to enable each team to do independent DB migration and rollback. These tables are serving prod traffic. One idea to achieve it is:

1. create one schema per team, and move existing tables to team specific schemas
2. each team manages independent DB migration of tables in the team's schema.
However, it doesn't seem like dbmate supports migration at the schema level (which is needed in 2). Is there a plan to add this support for Postgres?

Also, do you have any suggestion on the overall approach to achieve our goal?

thanks a lot,
-Jeff

**Comment by amacneil** [comment]
Hi!

I think there are a couple ways you could approach this. You're right that dbmate will always put the schema_migrations table in the public schema. However, you could:

a) I don't think there are any issues with having two separate people sharing the same schema with different sets of migrations, as long as none of the migrations have a conflicting version number. Since the migration versions are a timestamp by default, you're probably going to be safe there. 
b) You could create a separate database instead of a separate schema. This is very simple in postgres unless you have some extreme restrictions with your database hosting.

**Comment by jeff-cf** [comment]
Hi Adrian,

Thanks a lot for your suggestion!
a) Say, if team A commits migration A1, then team B commits migration B1, then A commits A2, and needs to rollback both A2 and A1, then it would rollback team B's migration B1 as well, which is a problem, correct?

b) Schema should work better for our case as there can be foreign key constraints. However, moving the existing tables to different schemas is still a challenge as these tables are serving prod traffic. Any recommendation?

**Comment by amacneil** [comment]
Regarding your response to (a) - no, I'm pretty sure dbmate will completely ignore B1 (assuming you are working from two separate codebases), because dbmate won't be able to find the migration file to revert it. Definitely test this first, but I'm pretty sure it will work exactly how you want it to.

Re (b) - that makes sense, in that case I think approach (a) might be the best one for you!

**Comment by jeff-cf** [comment]
> Regarding your response to (a) - no, I'm pretty sure dbmate will completely ignore B1 (assuming you are working from two separate codebases), because dbmate won't be able to find the migration file to revert it. Definitely test this first, but I'm pretty sure it will work exactly how you want it to.
> 
> Re (b) - that makes sense, in that case I think approach (a) might be the best one for you!

Thanks Adrian. Regarding (a), teams have separate codebases for their services, but all DB migration scripts share the same repo, so rolling back can be a problem.
