### ISSUE TITLE
Document usage inside Go code as a library.

### ISSUE THREAD

**Issue by fr3fou** [amacneil/dbmate#189]
I had to look in the `main.go` file to figure out how to properly implement using this as a library inside my Go code.
Here's what I ended up with:

```go
package main

import (
	"net/url"
	"os"

	"github.com/amacneil/dbmate/pkg/dbmate"
	_ "github.com/amacneil/dbmate/pkg/driver/mysql"
)

func main() {
	databaseURL, err := url.Parse(os.Getenv("DATABASE_URL"))
	if err != nil {
		panic(err)
	}

	migrator := dbmate.New(databaseURL)
	err = migrator.CreateAndMigrate()
	if err != nil {
		panic(err)
	}
}
```
Another thing I also stumbled upon is that I _have_ to use dbmate's mysql driver and not any generic mysql driver, such as `https://github.com/go-sql-driver/mysql`; Is there any particular reason for that?

**Comment by amacneil** [comment]
Yes, that's a pretty good summary of simple usage of dbmate as a library.

It's not well documented since dbmate is primarily intended to be used as a CLI tool, but you're of course welcome to use it as a library and it has been designed so that this should be easy (all CLI-specific code lives in `main.go`, and everything under `pkg/dbmate` can be easily imported).

Regarding your last question, the dbmate driver wraps `go-sql-driver/mysql`, but adds dbmate-specific logic so that we know how to do things like create the `schema_migrations` table, query existing migrations, etc (which differs between databases).
