### ISSUE TITLE
Allow specifying the template when creating a Postgres database

### ISSUE THREAD

**Issue by ohueter** [amacneil/dbmate#206]
It would be great if the Postgres database template could be specified when using `dbmate up`. Maybe via `dbmate up --template template1`?

I'm not familiar with most of the other databases supported by dbmate. Do similar mechanisms exist with these, or is this a very Postgres-specific feature request?

Background: We are setting up a new project using PostGIS and need to create the database with PostGIS extensions via `createdb -T template_postgis my_spatial_db` or `CREATE DATABASE my_spatial_db TEMPLATE=template_postgis`.

**Comment by ohueter** [comment]
It seems like we can get away with using `CREATE EXTENSION postgis;`. I rushed to opening an issue a little too quickly, sorry about that. 

I'm leaving this issue open, however, as the general idea may be interesting to others? Please feel free to close if that's not the case. Thank you for your work on dbmate, Adrian!

**Comment by amacneil** [comment]
Thanks for the report.

I think if it's possible to do this in a migration, then that is your best option. It's much easier to keep all the database creation logic in one place (the migration files), rather than worrying about whether a developer on your team forgot to set some special environment flag to request dbmate to create this extension, and then some of the migrations don't work because there is a missing extension. Also, if we supported arbitrary templates, there's no guarantee that they would even exist on a different machine.

I'll close this for now, but if anyone has another reason for needing templates that can't be solved in migration files, please comment.
