### ISSUE TITLE
Proposal: Having separation in timestamp formatting for readability

### ISSUE THREAD

**Issue by gmhafiz** [amacneil/dbmate#252]
## Issue 

Currently dbmate creates a new migration file with the following [format](https://github.com/amacneil/dbmate/blob/main/pkg/dbmate/db.go#L245)

```go
timestamp := time.Now().UTC().Format("20060102150405")
```

When you have a bunch of them it's hard to easily find a migration made in a specific month.

I propose having some separation between the year, month and day in the timestamp. For example:

 - `2006_01_02_150405`
 - `2006-01-02-150405`

These are still sortable (if all follows the same format). Complies with [`migrationVersion()`](https://github.com/amacneil/dbmate/blob/main/pkg/dbmate/db.go#L448) regex.

In my opinion, it is much easier to read the dates since we care YYYY_MM_DD the most.

![image](https://user-images.githubusercontent.com/1927253/147804563-536744f4-6bf5-4ac4-8faf-ef36cbd75527.png)

## Problem 

Obviously it it not backward-compatible because sorting with both separated and non-separated timestamp will not sort by date.

Unless something is done to parse the timestamp in place of [`sort.Strings(matches)`](https://github.com/amacneil/dbmate/blob/main/pkg/dbmate/db.go#L425) and sort them by date accordingly (which is easy), then, it can be backward compatible. I am unsure the impact to the records saved in `schema_migrations` table though.

**Comment by gmhafiz** [comment]
It appears [migrationversion](https://github.com/amacneil/dbmate/blob/main/pkg/dbmate/db.go#L448) is also affected. I handled that too in the following pull request.

https://github.com/amacneil/dbmate/pull/253

**Comment by gmhafiz** [comment]
I beginning to think that simply using `time.RFC3339` would be better.

- no spaces
- part of rfc standard and standard library
- includes timezone
- still can differentiate the year, month, day
- time is separated by colons

Once issue is how colon is handled under Windows because I remember powershell had difficulties a string containing colons needing to escape with backslash.

**Comment by amacneil** [comment]
The migration version isn't really supposed to be a human readable date, since the date is irrelevant to the migration contents. We just use a date-based version number so that two developers on different branches don't try to create "migration version 3".

You're free to name the migrations whatever you like, however I think we currently require the migration version to be numeric only. We could maybe expand that to support periods (i.e. to support https://github.com/amacneil/dbmate/issues/63 - open to a PR adding this). Outside of periods, I don't think it would be a good idea to support hyphens/colons/etc since it becomes harder to distinguish between the version string and the migration name. Colons in filenames also create portability issues (doesn't work on windows iirc).
