### ISSUE TITLE
Separate files for up and down portions of a migration

### ISSUE THREAD

**Issue by bever1337** [amacneil/dbmate#255]
Thanks for your time in advance. `dbmate` is a great product.

Is there a way to separate the up and down portion of a migration into separate files? From a portability perspective, it would be ideal to have SQL files that don't do an immediate tear down. For example: [Diesel](https://diesel.rs/guides/getting-started#setup-diesel-for-your-project).

**Comment by amacneil** [comment]
Thanks for the feedback!

It's not possible to have separate up and down migration files. I'm open to a PR adding this - maybe we just automatically detect if the files end with `.up.sql` and `.down.sql` we treat them as separate files?

It's personal preference, but I prefer keeping the up and down migration in the same file because I find it easier for editing and ensuring they match.

**Comment by bever1337** [comment]
Thank you @amacneil ! I appreciate the reply.

I'm going to close this ticket because the dbmate approach seems great even though it doesn't match my very particular business requirements.

**Comment by bever1337** [comment]
Sorry, that was my way of saying "I don't have the time to contribute this feature!" In my opinion, this represents dev environment opinions, not standards. `dbmate` seems just fine without this approach. Thank you again
