### ISSUE TITLE
Feature: Nested directories in migration directory?

### ISSUE THREAD

**Issue by JanmanX** [amacneil/dbmate#273]
In a project with a lot of migration files, it would be great to structure those in separate sub-directories, such as:
```
├── 0001.sql
├── 0005.sql
├── week1
│   └── 0002.sql
└── week2
    ├── 0003.sql
    └── 0004.sql
```

I know that it is possible to specify the migration directory, but this makes the other folders "invisible" to DBMate. While this still works and won't (seem to) break DBMate, it would be great to have this work natively.

I would like to volunteer to implement this feature, if needed.

**Comment by rohitpaulk** [comment]
I think this is a good idea, don't see a downside to it as long as we're clear that directory naming doesn't affect the order (i.e. files are still ordered by filenames irrespective of what directory they're in). 

@amacneil thoughts?

**Comment by amacneil** [comment]
Only potential source of confusion I can see:

Would you expect the migrations to be applied in alphabetical order including directory name, or ignore the directory and only look at the version number?

**Comment by JanmanX** [comment]
Personally I would prefer applying migrations using the version number, regardless which directory they come from.
The advantages I can think of:
- More freedom how to structure the sub-directories. You could structure the migrations in directories: `functions`, `tables`, `roles`, etc., and not worry which order they are applied in.
- The migration versions stay the same and can further moved around without worrying of breaking the ordering.
- It might be more intuitive to figure out which order to apply migrations in (less complexity)

**Comment by amacneil** [comment]
My fear is that another group of people will expect the opposite behavior - if you have folders named "week1", "week2", etc - why wouldn't they be applied in order?

Likewise if people organized their migrations into version number folders - "v1.0", "v1.1", etc. Or even worse, they might expect us to respect semver ordering ("v1.23" folder being applied after "v1.5").

On a tangent: if you have a lot of migrations (e.g. project that has been under development for years), you can always consolidate your old migrations. Just take the current state of the database and put it in a new migration file (making sure all the DDL statements use "if exists" where appropriate so that they won't make any actual changes to existing databases), then delete all the old migration files.

**Comment by CasperLindinger** [comment]
What if you added a command like `dbmate new-dir week1`, which adds a version number to a directory like the migrations?

```
├── 0001.sql    
├── 0005.sql    
├── 0001_week1  
│   └── 0002.sql
└── 0002_week2  
    ├── 0003.sql
    └── 0004.sql
```

Then perhaps it's matter of starting with the root directory and then go through the version numbers on the directories

**Comment by Enrico204** [comment]
**My opinion**: this feature may introduce a lot of complexity (e.g. the order of execution, see above) and may provide a very little gain.

If the issue is that migrations tends to accumulate in time, there are two ways of handling this:

* consolidating migrations (they will remain in your git history)
* archive them (even in directories like you proposed) once they are applied - you can do this manually

In both cases there is no need for this tool to support other structures. The more a tool is complex to use, the more error you will have. YMMV

**Comment by rohitpaulk** [comment]
^ Yeah, I feel the same after reading the comments above.

**Comment by JanmanX** [comment]
I understand that the complexity introduced by this would greatly outweigh the questionable advantages that this provides.

Thanks for your input! 

Closing.
