### ISSUE TITLE
Dbmate Unable to Create SchemaMigrations Table

### ISSUE THREAD

**Issue by dilutedev** [amacneil/dbmate#444]
**While running `dbmate up` I get this error Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"schema_migrations"' at line 1**

- Version: 8
- Database: mysql
- Operating System: macos

**Steps To Reproduce**
`Just run dbmate up with mysql:v8

**Should migrate data but it logs that error**

**Comment by ebuckthal** [comment]
My guess is that you have [ANSI_QUOTES](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_ansi_quotes) SQL mode enabled. It's not a default flag in MYSQL 8 itself, but I've noticed some database providers turn it on by default.

I believe `dbmate` should use back ticks instead of double quotes in these instances

**Comment by prayog-exc** [comment]
Did you ever find a solution to this @dilutedev ? I'm running into the same issue.

**Comment by dilutedev** [comment]
> Did you ever find a solution to this @dilutedev ? I'm running into the same issue.

No, I didnt

**Comment by dilutedev** [comment]
> Did you ever find a solution to this @dilutedev ? I'm running into the same issue.

No, I didnt

**Comment by toru** [comment]
I came across this problem with mysqld (8.0.30) that was configured with the `ANSI_QUOTES` sql_mode. This issue is not limited to just the `schema_migrations` table, and it affects most commands because `schema_migrations` related queries are integral to dbmate.

Here is the explanation of the problem, and how I solved it. First, a demonstration to show that the ANSI_QUOTES sql_mode was enabled.

```
> SELECT @@sql_mode;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                                                      |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)

> SELECT @@GLOBAL.sql_mode;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| @@GLOBAL.sql_mode                                                                                                                                                               |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.002 sec)
```

According to the [ANSI_QUOTES documentation](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_ansi_quotes), double quote characters cannot be used to express string literals.

> Treat " as an identifier quote character (like the ` quote character) and not as a string quote character. You can still use ` to quote identifiers with this mode enabled. With ANSI_QUOTES enabled, you cannot use double quotation marks to quote literal strings because they are interpreted as identifiers.

Therefore removing ANSI_QUOTES from sql_mode has remedied the issue. There are multiple ways to do this. In my case, this was a managed MySQL instance so I made the change on the provider's Web UI. After the change, Dbmate is now happily functioning. Having said that, first check with your team since there could be a business requirement to enable ANSI_QUOTES.

```
> dbmate --url "mysql://redacted/database" -s schema.sql -d . migrate
...
Writing: schema.sql
```

To call this a dbmate bug or not is debatable. FWIW, back in the day, I think the queries produced by dbmate were quoted differently. I imagine that's why some people are reporting that things worked fine in older versions.

**Comment by toru** [comment]
I came across this problem with mysqld (8.0.30) that was configured with the [ANSI_QUOTES](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_ansi_quotes) sql_mode. This issue affects most commands because `schema_migrations` related queries are integral to dbmate.

Here is the explanation of the problem, and how I solved it. First, a demonstration to show that the ANSI_QUOTES sql_mode was enabled.

```
> SELECT @@sql_mode;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                                                      |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)

> SELECT @@GLOBAL.sql_mode;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| @@GLOBAL.sql_mode                                                                                                                                                               |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.002 sec)
```

According to the [ANSI_QUOTES documentation](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_ansi_quotes), double quote characters cannot be used to express string literals.

> Treat " as an identifier quote character (like the quote character) and not as a string quote character. You can still use to quote identifiers with this mode enabled. With ANSI_QUOTES enabled, you cannot use double quotation marks to quote literal strings because they are interpreted as identifiers.

Therefore removing ANSI_QUOTES from sql_mode has remedied the issue. There are multiple ways to do this. In my case, this was a managed MySQL instance so I made the change on the provider's Web UI. Dbmate is happily functioning after the change. Having said that, first check with your team since ANSI_QUOTES could be enabled due to a requirement of some kind.

```
> dbmate --url "mysql://redacted/database" -s schema.sql -d . migrate
...
Writing: schema.sql
```

To call this issue a dbmate bug or not is debatable. FWIW, back in the day, I think the queries produced by dbmate were quoted differently. I imagine that's why some people are reporting that things worked fine in older versions.

**Comment by toru** [comment]
Apologies, the double quote reference might be red-herring. Here is a real query produced by dbmate's MySQL driver:

```sql
create table if not exists `schema_migrations` (version varchar(128) primary key)
```

This complies with ANSI_QUOTES, and I confirmed locally that the query is accepted. I'll take a closer look and report back later. Perhaps there is a sneaky query somewhere.

**Comment by toru** [comment]
@dilutedev @prayog-exc FYI, I submitted a PR that addresses this issue: https://github.com/amacneil/dbmate/pull/475
