### ISSUE TITLE
ClickHouse Cloud https connection doesn't work

### ISSUE THREAD

**Issue by ddamirel** [amacneil/dbmate#447]
**Description**
When I try to connect to Clickhouse Cloud I receive the following error:
Error: [handshake] unexpected packet [72] from server

- Version: dbmate version 2.3.0
- Database: ClickHouse v23.3
- Operating System: MacOS

**Steps To Reproduce**
dbmate -u "clickhouse://default:dummy@dummy.us-east-1.aws.clickhouse.cloud:8443/default?secure=true" up

Connection string in Clickhouse Cloud looks like this:
curl --user 'default:<password>' --data-binary 'SELECT 1' https://dummy.us-east-1.aws.clickhouse.cloud:8443
But if I will add https:// to address dbmate will give an error:
Error: dial tcp: address https::9000: too many colons in address

**Comment by FatherCandle** [comment]
Hi @ddamirel,
Please notice that you are passing ClickHouse's https port (8443) with the database URL.
As you can see from the error given, the expected protocol is TCP and not https.

please reference: https://clickhouse.com/docs/en/guides/sre/network-ports
Since you want to work with SSL/TLS you should try using port 9440.

**Comment by ddamirel** [comment]
9440 port solved this issue, thank you @FatherCandle
