### ISSUE TITLE
Command line option --no-dump-schema does not work

### ISSUE THREAD

**Issue by spajak** [amacneil/dbmate#48]
Executing:

`$ bin/dbmate migrate --no-dump-schema`

Gives:

```
Incorrect Usage: flag provided but not defined: -no-dump-schema

NAME:
   dbmate migrate - Migrate to the latest version

USAGE:
   dbmate migrate [arguments...]
Error: flag provided but not defined: -no-dump-schema
```

**Comment by wunderkind2k1** [comment]
We noticed that the schema.sql is never dumpe, unless you call dbmate dump specifically too.

To add to that on our machine the dump is not working because the flag '-column-statistics=0' is not set (https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109).

A quick view into https://github.com/amacneil/dbmate/blob/4710a35da11ed4b2428e865176e9240ea7e6f387/pkg/dbmate/mysql.go made me think it should be added to the function `mysqldumpArgs(u *url.URL) []string`.

**Comment by amacneil** [comment]
I did some research into this, and was able to reproduce using mysqldump client version 8 against a mysql 5.7 server.

Unfortunately, the `--column-statistics=0` arg is not supported by mysqldump 5.x and causes an error, so we can't make that the default without adding some messy client feature detection logic. 

For now the best workaround to this issue is to either use a matching mysqldump version on your client as your server (generally a good idea), or set the following in your local `~/.my.cnf` file:

```
$ cat ~/.my.cnf
[mysqldump]
column-statistics=0
```

**Comment by khairaf** [comment]
I also got the same error, when executing: 
```
DATABASE_URL=postgres://postgres:root@127.0.0.1:5432/mydb?sslmode=disable dbmate -d db/migrations migrate --no-dump-schema
```

```
Incorrect Usage: flag provided but not defined: -no-dump-schema

NAME:
   dbmate migrate - Migrate to the latest version

USAGE:
   dbmate migrate [arguments...]
Error: flag provided but not defined: -no-dump-schema
```
I am using postgres

**Comment by amacneil** [comment]
@khairaf you need to pass --no-dump-schema before the word migrate, because it is a global flag.

**Comment by khairaf** [comment]
oh my bad, thank you so much for the reply @amacneil. it works now.

**Comment by wunderkind2k1** [comment]
Hey @spajak: To me it looks like this issue is closable isn't it?
