### ISSUE TITLE
Is there a command to do a dry-run?

### ISSUE THREAD

**Issue by atedja** [amacneil/dbmate#59]
Wondering if there is a command if a particular target DB is consistent with the current migrations, without doing destructive changes like `dbmate up`.

**Comment by amacneil** [comment]
We have discussed this a bit in https://github.com/amacneil/dbmate/pull/45. This would run the migration inside a transaction, then roll back the migration afterwards. Only postgres supports running migrations inside a transaction.

I'm not convinced this approach (apply then migrate) is a good idea though, because I don't know the performance impact if it were to be run on a large database. It would require further testing before I'd be comfortable adding it.

What is your use case?

**Comment by atedja** [comment]
The use case was to test if the database my env is pointing to is up-to-date with the schema, and the only way I can do this now is to execute the actual migration. When you are dealing multiple database envs, this situation can come up often.

Maybe use a docker container, and execute it there, then compare the `schema.sql` from the docker with the database it's pointing to?

**Comment by camerondavison** [comment]
i would like to see something that just enumerated out which migrations are going to run. so that i know that the `schema_migrations` is in the expected state.

**Comment by emmetog** [comment]
:+1: Our use case is to give us a chance to have a look at the full SQL that would be run were we to hit the button.

**Comment by vrajanap** [comment]
One alternative way is to check if the db contains all the migrations names that are available to be applied.

**Comment by amacneil** [comment]
We added the `dbmate status` command in https://github.com/amacneil/dbmate/pull/120, which will allow you to check if there are pending migrations. This isn't quite the same as a full "dry run", but I expect it will solve most use cases.
